#!/bin/bash

# Called after user changes app settings in fnOS
# Update accessible paths file for Go process to read dynamically
echo "${TRIM_DATA_ACCESSIBLE_PATHS:-}" > "${TRIM_PKGVAR}/accessible_paths"

exit 0
